### ISSUE TITLE
Client disconnect when using /tick freeze, or pausing the game 

### ISSUE THREAD

**Issue by lemonnade0** [gabehxd/PauseGameFabric#2] opened 2024-06-19 10:10 UTC
When I have the mod installed on my client and join my Fabric 1.21 server with this mod installed, the client times out when pausing the game or using the /tick freeze command. The issue replicates without the client-side mod but doesn't without the server-side mod.
Server log: https://pastebin.com/vecXmwhR

**Comment by gabehxd** [comment] 2024-06-19 11:21
Would you be able to provide logs from the client?

**Comment by lemonnade0** [comment] 2024-06-19 11:38
Video of the issue: https://drive.google.com/file/d/1Oja_qufL74Xzc7S6MlpKlAyXi6Hn53d7/view 
Client log: https://pastebin.com/yyqce83G
Server log: https://pastebin.com/RgNxNPAJ

**Comment by gabehxd** [comment] 2024-06-20 08:02
Could you apply the setting `-Dmixin.debug.export=true` to your server flags and send me the output of the `.mixin.out` folder and/or possibly also all the mods installed onto your server? My current suspicion is a compatibility issue with some other mod on your server as I can't reproduce this issues on my server.

**Comment by lemonnade0** [comment] 2024-06-21 07:23
[crash-2024-06-21_06.27.43-server.txt](https://github.com/user-attachments/files/15923658/crash-2024-06-21_06.27.43-server.txt)
I got this server crash while testing the mod again - sure if that's related to the fact that it kicked me out before, or gave me this new error one time instead of the usual one. 
![image](https://github.com/gabehxd/PauseGameFabric/assets/54548812/a9dca7f6-5759-4904-8923-fe0bbcac82d7)
Server logs: https://pastebin.com/yDBuzLgq

I tested it again, and recorded the session. It didn't crash for a while, but started crashing when I moved quickly right before I paused. https://drive.google.com/drive/folders/1P335jCfICc4X9x9QtvwnI6P3DOWHjOM2 
I also got another new error once while I was recording this: 
![image](https://github.com/gabehxd/PauseGameFabric/assets/54548812/8bff2ac2-7493-461a-a7da-1bbeb037947d)

[crash-2024-06-21_06.52.58-server.txt](https://github.com/user-attachments/files/15924114/crash-2024-06-21_06.52.58-server.txt)
[crash-2024-06-21_06.49.11-server.txt](https://github.com/user-attachments/files/15924115/crash-2024-06-21_06.49.11-server.txt)
[crash-2024-06-21_06.58.26-server.txt](https://github.com/user-attachments/files/15924116/crash-2024-06-21_06.58.26-server.txt)
Here are some more crash reports ^
[2024-06-21-7.log.gz](https://github.com/user-attachments/files/15924128/2024-06-21-7.log.gz)
[2024-06-21-6.log.gz](https://github.com/user-attachments/files/15924129/2024-06-21-6.log.gz)
[2024-06-21-5.log.gz](https://github.com/user-attachments/files/15924130/2024-06-21-5.log.gz)
[2024-06-21-4.log.gz](https://github.com/user-attachments/files/15924131/2024-06-21-4.log.gz)
and a couple of latest logs.
And the .mixin.out folder: [mixin.out.zip](https://github.com/user-attachments/files/15924159/mixin.out.zip)
And here's my mods folder straight from the server: https://drive.google.com/file/d/1eAreT8zPGHiWrRT1Nk7KNdajukz0V41J/view?usp=drive_link

**Comment by lemonnade0** [comment] 2024-06-21 07:27
It seems that this issue is at least partially related to high movement speed and/or high CPU load. It's way more complicated to reproduce now that my Dynmap task finished, and there's less CPU load on the server, but it's still possible if I move quickly. I tried replicating the issue without this mod, but I couldn't even do it when using /tick freeze because /tick freeze doesn't freeze players in vanilla.

**Comment by gabehxd** [comment] 2024-06-21 10:13
/tick freeze should not be used manually in most cases, I'll try to add some checks to ensure some functions still work when it is enabled manually but I high recommend against it. Just to confirm all these logs from using /tick freeze or are they also using the pause/esc menu to freeze the game?

**Comment by lemonnade0** [comment] 2024-06-21 10:50
Almost all of the crashes were from using the pause menu. I used the /tick freeze command to invoke the pause manually a couple of times, but when I troubleshooted the issue today it was way easier to replicate the issue by just using the pause menu.

**Comment by gabehxd** [comment] 2024-06-22 03:34
Could i have you try this version when you get chance? this only needs to be installed on the serve [PauseGame-3.0.0.zip](https://github.com/user-attachments/files/15934947/PauseGame-3.0.0.zip)

**Comment by gabehxd** [comment] 2024-06-22 03:35
Using this version i haven't been able to reproduce this issue on my end

**Comment by lemonnade0** [comment] 2024-06-22 04:03
> this only needs to be installed on the serve
Should I use the old version on the client, or no mod at all? I tried it with a vanilla client, and with a client with v2.0.1 - with no mod on the client it didn't pause at all, and with v2.0.1 I managed to break it in a minute.

**Comment by gabehxd** [comment] 2024-06-22 06:25
I completely rewrote the way the player movement gets handled.. go ahead an try this 
[PauseGame-3.0.0.jar.zip](https://github.com/user-attachments/files/15935569/PauseGame-3.0.0.jar.zip)

**Comment by gabehxd** [comment] 2024-06-22 06:26
I was also able to reproduce the issue but never consistently for some reason?

**Comment by lemonnade0** [comment] 2024-07-01 17:18
I conducted minimal testing which did not result in any crashes. However, since I recently upgraded the server hardware, this testing may not be conclusive if the issue is related to performance.

**Comment by gabehxd** [comment] 2024-07-02 06:19
It's possible it's a server upgrade but the code that seemed to cause the issue was just rewritten from scratch, for now I'll close this issue since it *seems* to be resolved but feel free to reopen if you're able to reproduce the issues again on 3.0.0, Thanks for testing!

**Closed as completed by gabehxd** 2024-07-02 06:19 UTC
Labels: bug
